version: '3.8'

services:
  chat-app:
    build: .
    container_name: chat-system
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DB_HOST=mongodb
      - DB_PORT=27017
      - DB_NAME=chatdb
    volumes:
      - ./logs:/app/logs
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - chat-network

  mongodb:
    image: mongo:6.0-jammy
    container_name: chat-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=chatdb
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    restart: unless-stopped
    networks:
      - chat-network

  # Optional: MongoDB Admin Interface
  mongo-express:
    image: mongo-express:latest
    container_name: chat-mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - chat-network

volumes:
  mongodb_data:
    driver: local

networks:
  chat-network:
    driver: bridge
